---
- name: "{{ myansible_prefix_task_name }}Include OS {{ ansible_os_family }} specifics variables."
  include_vars: "{{ ansible_os_family }}.yml"

- name: "{{ myansible_prefix_task_name }}Install devtools packages"
  package:
    name: "{{ item }}"
    state: present
    purge: true
  with_items:
    - "{{ packages_name }}"
